package entity;
// Generated Oct 24, 2017 6:39:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
)
public class Address  implements java.io.Serializable {


     private long id;
     private long housekey;
     private Long streetid;
     private Set humans = new HashSet(0);

    public Address() {
    }

	
    public Address(long id, long housekey) {
        this.id = id;
        this.housekey = housekey;
    }
    public Address(long id, long housekey, Long streetid, Set humans) {
       this.id = id;
       this.housekey = housekey;
       this.streetid = streetid;
       this.humans = humans;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="housekey", nullable=false)
    public long getHousekey() {
        return this.housekey;
    }
    
    public void setHousekey(long housekey) {
        this.housekey = housekey;
    }

    
    @Column(name="streetid")
    public Long getStreetid() {
        return this.streetid;
    }
    
    public void setStreetid(Long streetid) {
        this.streetid = streetid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getHumans() {
        return this.humans;
    }
    
    public void setHumans(Set humans) {
        this.humans = humans;
    }




}


