package entity;
// Generated Oct 22, 2017 10:35:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
)
public class Address  implements java.io.Serializable {


     private long id;
     private Streets streets;
     private long housekey;
     private Set humans = new HashSet(0);

    public Address() {
    }

	
    public Address(long id, Streets streets, long housekey) {
        this.id = id;
        this.streets = streets;
        this.housekey = housekey;
    }
    public Address(long id, Streets streets, long housekey, Set humans) {
       this.id = id;
       this.streets = streets;
       this.housekey = housekey;
       this.humans = humans;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="streetid", nullable=false)
    public Streets getStreets() {
        return this.streets;
    }
    
    public void setStreets(Streets streets) {
        this.streets = streets;
    }

    
    @Column(name="housekey", nullable=false)
    public long getHousekey() {
        return this.housekey;
    }
    
    public void setHousekey(long housekey) {
        this.housekey = housekey;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getHumans() {
        return this.humans;
    }
    
    public void setHumans(Set humans) {
        this.humans = humans;
    }




}


