package entity;
// Generated Oct 22, 2017 10:35:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Streets generated by hbm2java
 */
@Entity
@Table(name="streets"
)
public class Streets  implements java.io.Serializable {


     private long id;
     private String streetname;
     private Set addresses = new HashSet(0);

    public Streets() {
    }

	
    public Streets(long id, String streetname) {
        this.id = id;
        this.streetname = streetname;
    }
    public Streets(long id, String streetname, Set addresses) {
       this.id = id;
       this.streetname = streetname;
       this.addresses = addresses;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="streetname", nullable=false)
    public String getStreetname() {
        return this.streetname;
    }
    
    public void setStreetname(String streetname) {
        this.streetname = streetname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="streets")
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


